[package]
name = "lsp-bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.2.1"
futures = "0.3.34"
httparse = "1.10.1"
log = "0.4.34"
memchr = "2.8.3"
serde = "1.0.229"
serde_json = "*"
tokio-util = "0.7.19"
tower = { version = "0.5.3", features = ["full"] }
tower-lsp-server = "0.23.0"

[dependencies.tokio]
version = "1.53.1"
features = ["full"]
